[package]
name = "magic-link"
version = "0.1.0"
authors = ["kyle.smallwood@gmail.com <kyle.smallwood@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.19"
serde = "1.0.98"
approveapi = "1.0.3"
failure = "0.1.5"
futures = "0.1.25"